### GET
GET 127.0.0.1:5100/api/v1

### POST
POST localhost:5100/api/v1/?b=users
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### GET
GET localhost:5100/api/v1/users?eq.value(content)
